spring.application.name=helloworld
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

# Exclude individual endpoints with comma-delimited list

management.endpoints.web.exposure.exclude=health,info